// <auto-generated />
using BlackJackDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlackJackDAL.Migrations
{
    [DbContext(typeof(BlackJackContext))]
    [Migration("20211104103708_AddedTotalCurrencyHighscore")]
    partial class AddedTotalCurrencyHighscore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlackJackDAL.DealerInfo", b =>
                {
                    b.Property<int>("DealerInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsGameWon")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("DealerInfoId");

                    b.ToTable("DealerInfo");
                });

            modelBuilder.Entity("BlackJackDAL.PlayedGame", b =>
                {
                    b.Property<int>("PlayedGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsGameWon")
                        .HasColumnType("bit");

                    b.Property<string>("PlayerNickName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PlayedGameId");

                    b.HasIndex("PlayerNickName");

                    b.ToTable("PlayedGames");
                });

            modelBuilder.Entity("BlackJackDAL.Player", b =>
                {
                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCurrency")
                        .HasColumnType("int");

                    b.HasKey("NickName");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BlackJackDAL.PlayedGame", b =>
                {
                    b.HasOne("BlackJackDAL.Player", null)
                        .WithMany("PlayedGames")
                        .HasForeignKey("PlayerNickName");
                });

            modelBuilder.Entity("BlackJackDAL.Player", b =>
                {
                    b.Navigation("PlayedGames");
                });
#pragma warning restore 612, 618
        }
    }
}
